# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e8d5b5c2210a8c872f5b13adac904d3d4b572cfd46140c47187237396be3151d5f5e3b623bad3a78fce70207e02f613da66abe97ceebbcef9412cdcc2b6bad

test:
  secret_key_base: 3461a6995471a22e4cb39ab07a45e062adbf22d5761fb52d27057c2b01ea2ce3dc8c6b57e4eae4fe0402e58b520b66f0a392782dfa574b26ad45b47d3f66694e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
